# Generated by Django 5.2.3 on 2025-06-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='processed_video',
            field=models.FileField(blank=True, null=True, upload_to='processed/%y'),
        ),
    ]
